# Generated by Django 6.0.5 on 2026-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dodo_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
