# Generated by Django 6.0.5 on 2026-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_userprofile_dodo_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='scans_used',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_spend',
            field=models.FloatField(default=0.0),
        ),
    ]
