# Generated by Django 6.0.5 on 2026-05-06 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_remove_userprofile_scans_used_userprofile_api_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_scans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_scan_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
