# Generated by Django 6.0.5 on 2026-05-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_historicalscanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
