# Generated by Django 6.0.5 on 2026-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_historicaluserprofile_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='api_spend',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='api_spend',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
