import React from 'react';
import { Scale } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-900 text-gray-300 py-12 px-6">
      <div className="max-w-3xl mx-auto bg-gray-800/50 border border-gray-700 rounded-2xl p-10 shadow-2xl backdrop-blur-xl">
        
        <div className="flex items-center gap-4 border-b border-gray-700 pb-6 mb-8">
          <Scale className="w-10 h-10 text-blue-500" />
          <div>
            <h1 className="text-3xl font-black text-white tracking-tighter">Terms and Conditions</h1>
            <p className="text-sm text-gray-500 mt-1">Effective Date: May 7, 2026</p>
          </div>
        </div>

        <div className="space-y-8 prose prose-invert prose-blue max-w-none">
          
          {/* CRITICAL DISCLAIMER BOX */}
          <section className="bg-red-900/10 border border-red-500/30 p-6 rounded-xl">
            <h2 className="text-xl font-bold text-red-400 mb-2 mt-0">NO LEGAL ADVICE</h2>
            <p className="text-red-200/80 text-sm leading-relaxed mb-0">
              Vigilate provides automated, AI-assisted text analysis and clause extraction. The Service is for informational purposes only and does not constitute legal advice, legal opinions, or recommendations. No attorney-client relationship is formed by using the Service. We are not liable for any misinformation, inaccuracies, or omissions generated by the AI analysis. Users must not rely on the Service as a substitute for professional legal counsel. Always consult with a qualified attorney before signing or executing any legal or binding agreements.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white border-b border-gray-700/50 pb-2 mb-4">1. Introduction & Acceptance</h2>
            <p>
              Welcome to Vigilate. These Terms and Conditions govern your use of our website located at https://vigilate.vercel.app. By accessing or using our Service, you agree to be bound by these Terms. Our Service is intended only for access and use by individuals at least 18 years old.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white border-b border-gray-700/50 pb-2 mb-4">2. Service Access and Subscriptions</h2>
            <p>
              Some parts of the Service are billed on a subscription basis. You will be billed in advance on a recurring and periodic basis. We reserve the right to modify, suspend, or discontinue the Service at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white border-b border-gray-700/50 pb-2 mb-4">3. Prohibited Uses</h2>
            <p>You may not use our Service:</p>
            <ul className="list-disc pl-5 space-y-2 text-sm">
              <li>For any unlawful purpose or to solicit others to perform unlawful acts.</li>
              <li>To infringe upon or violate our intellectual property rights or the intellectual property rights of others.</li>
              <li>To upload or transmit viruses or any other type of malicious code.</li>
              <li>To interfere with or circumvent the security features of the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white border-b border-gray-700/50 pb-2 mb-4">4. Limitation of Liability & Indemnification</h2>
            <p>
              In no event shall Vigilate, nor its directors, employees, or affiliates, be liable for any indirect, incidental, punitive, or consequential damages. In no event shall our liability exceed the amount paid by you, if any, for accessing or using the Service during the twelve (12) months immediately preceding the date of the claim or one hundred dollars ($100), whichever is greater.
            </p>
            <p>
              You agree to defend, indemnify, and hold harmless Vigilate from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white border-b border-gray-700/50 pb-2 mb-4">5. Dispute Resolution & Governing Law</h2>
            <p>
              These Terms shall be interpreted and governed by the laws of Sri Lanka. Any dispute arising out of or relating to these Terms shall be resolved through binding arbitration. You agree to waive your right to a jury trial and to participate in a class action lawsuit.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white border-b border-gray-700/50 pb-2 mb-4">6. Contact Information</h2>
            <p>If you have any questions about these Terms, please contact us at <strong>architechsystems.lk@gmail.com</strong>.</p>
          </section>

        </div>
      </div>
    </div>
  );
}